import express from 'express';
import authUser from '../middlewares/auth.middleware.js'
import * as interviewaiController from '../controllers/interview.ai.controller.js'
import upload from '../middlewares/pdf.file.middleware.js';

const interviewRouter = express.Router();


/**
 * @route POST /api/interview/
 * @desc Generate a personalized AI interview report using the provided job description, resume, and self-description.
 * @access Private
 */
interviewRouter.post('/', authUser, upload.single("resume") ,interviewaiController.generateInterviewReportController);

/**
 * @route GET /api/interview/report/:interviewId
 * @desc Retrieve a specific interview report by its unique ID.
 * @access Private
 */
interviewRouter.get('/report/:interviewId', authUser, interviewaiController.getInterviewReportByIdController);

/**
 * @route GET /api/interview/all-reports
 * @desc Retrieve all interview reports generated by the authenticated user.
 * @access Private
 */
interviewRouter.get('/all-reports' , authUser , interviewaiController.getAllInterviewReportsController);


interviewRouter.post('/resume/pdf/:interviewId', authUser, interviewaiController.generateResumePdfController)

export default interviewRouter